### PR TITLE
add LeanbackLauncher

### PR DESCRIPTION
**Pull request by mikey0000**

### CODE REVIEW

**Comment by ayufan** [comment]
hm?

**Comment by mikey0000** [comment]
I noticed afterward that the LeanbackLauncher was under the fugu directory, I will have another PR with some updated apk's that needed replacing to work on Nougat.

**Comment by ayufan** [comment]
mikey0000: I do not use that for Nougat :) Instead I use packages from OpenGapps which are externally maintained and updated.

**Comment by mikey0000** [comment]
Oh right, I was having issues with gapps so decided to try using this. Almost have it working perfectly. Play store keeps crashing but at least google play music now works.

**Comment by ayufan** [comment]
Oh. Nice. So you did use old `proprietary_vendor_google_atv`? I used OpenGapps, because it works reliably with Regular and TV builds.

Maybe we should identify what we miss in OpenGapps and patch them?

**Comment by mikey0000** [comment]
Yes agreed. I used the nougat branch of this. For a start use the Music apk from here as it actually works or make sure we use the leanback version from opengapps. The play store behaves completely different and I get a ton more options but its currently crashing, will do some playing around today.

**Comment by mikey0000** [comment]
Also not sure if you are getting crashes with the webviewGoogle but the webviewGoogle in this branch works

**Comment by ayufan** [comment]
I do not. I was getting before, but then it was a problem of overlays and overriding built-in Android packages.

**Pull request closed without merging**
